server {
    listen 80;
    server_name guidely.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen 443 quic reuseport;

    server_name guidely.ru;

    ssl_protocols TLSv1.3;
    ssl_early_data on;
    ssl_certificate /etc/letsencrypt/live/guidely.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guidely.ru/privkey.pem;

    http2 on;
    http3 on;
    quic_retry on;
    quic_gso on;

    add_header Alt-Svc 'h3=":443"; ma=86400, h3-29=":443"; ma=86400' always;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        expires 1y;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
        add_header Cache-Control "public, no-transform";
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
