server {
    listen 80;
    listen 443 ssl http2;
    listen 443 quic reuseport;

    server_name guidely.ru;

    ssl_certificate /etc/letsencrypt/live/guidely.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guidely.ru/privkey.pem;

    add_header Alt-Svc 'h3=":433; ma=86400"';

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
